// Scanner module
// Take the source pattern string and generate tokens as needed
pub mod scanner;

// Parser module
// Take the tokens stream generated by the scanner
// and transform it into a syntax tree
pub mod parser;
